# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1346ad1aebcc2ed44faf11ba6ab725ad7d2d85864b5112bef910712acadbb177c67171ee7161714ec40793759db4a61ecbae7825e766f4ef9e8839f6f75b9912

test:
  secret_key_base: d80e94ecee93d0b64b1b50e8b0029b9950cc0589cb086e939ddfd88d5483ee6ce9f2fe58c96f6091d2e2ede279486376644bef9657a6a5c02c7378fd11eb29d9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
